#!/bin/bash

function GetOne()
{
	local fill="$1"
	local run="$2"

	# make work directory
	local dir="$top_dir/fill_$fill/run_$run/"
	mkdir -p "$dir"

	# get input files
	input_files=""
	for d in `eos ls "$eos_dir/$run"`
	do
		f="$run/$d/reco.root"

		if [ -n "$input_files" ]
		then
			input_files="$input_files,\n"
		fi

		input_files="${input_files}    \"root://eostotem.cern.ch/${eos_dir}/${f}\""
	done

	# make config with input files
	(
		echo "import FWCore.ParameterSet.Config as cms"
		echo ""
		echo "input_files = cms.vstring("
		echo -e "$input_files"
		echo ")"
	) > "$dir/input_files.py"

	# if not present, make (default) config
	cat "config_template.py" | sed "\
			s|\$fill|$fill|;\
			s|\$dataset|run $run|;\
		" > "$dir/config.py"
}

#----------------------------------------------------------------------------------------------------

top_dir="../data/alig"
eos_dir="/eos/totem/data/ctpps/reconstruction/alignment_run_version2"

GetOne "4828" "10077"
GetOne "4828" "10079"
GetOne "4828" "10080"
GetOne "4828" "10081"
GetOne "4828" "10082"
