#!/bin/bash

eos_dir="/eos/totem/data/ctpps/reconstruction/2016/preTS2_alignment_data/version1"

function BuildOneDir()
{
	local tag="$1"
	local selection="$2"
	local top_dir="$3"

	fill=${tag#fill_}
	fill=${fill%%_*}

	stream=${tag%%.*}
	stream=${stream##*_}

	echo "* $fill, $stream"

	# make work directory
	dir="$top_dir/fill_$fill/$stream/"
	mkdir -p "$dir"

	# make config with input files
	(
		echo "import FWCore.ParameterSet.Config as cms"
		echo ""
		echo "input_files = cms.vstring("
		for f in `eos ls "$eos_dir"|grep $tag|grep "$selection.root"`
		do
			echo "    \"root://eostotem.cern.ch/${eos_dir}/${f}\","
		done
		echo ")"
	) > "$dir/input_files.py"

	# if not present, make (default) config
	cat "config_template.py" | sed "\
			s|\$fill|$fill|;\
			s|\$dataset|$stream|;\
		" > "$dir/config.py"
}

#----------------------------------------------------------------------------------------------------

function BuildOneGroup()
{
	local selection="$1"
	local top_dir="$2"

	for tag in `eos ls "$eos_dir"|grep "$selection.root"|sed "s|fill_||;s|\..*$||"|uniq`
	do
		BuildOneDir "$tag" "$selection" "$top_dir"
	done

}

#----------------------------------------------------------------------------------------------------

BuildOneGroup "reduction_margin" "../data/phys_margin"

echo "-----------------------"

BuildOneGroup "reduction" "../data/phys_no_margin"
